[versions]

agp = "8.3.2"
android-x-test = "1.6.1"
android-x-testrules = "1.6.1"
android-x-test-ext-junitktx = "1.2.1"
android-x-testrunner = "1.6.1"
android-x-annotation = "1.8.0"
android-x-test-espresso = "3.6.1"
appcompat = "1.7.0"
awaitility = "4.1.0"
android-core-ktx = "1.13.1"
gson = "2.11.0"
hamcrest = "2.2"
jackson-core = "2.13.3"
jackson-module = "2.13.3"
json-assert = "1.5.0"
junit = "4.13.2"
kotlin = "1.8.22"
kotlinx-coroutines-core = "1.8.0"
kotlinx-serialization-json = "1.5.1"
material = "1.12.0"
mockito-kotlin = "4.0.0"
mockito = "4.0.0"
mockk = "1.13.7"
moshi = "1.13.0"
robolectric = "4.12.1"
work = "2.9.0"
runner = "1.0.2"
com-android-support-test-espresso-espresso-core = "3.0.2"
appcompat-v7 = "28.0.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-core" }

android-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "android-core-ktx" }
android-x-test = { group = "androidx.test", name = "core", version.ref = "android-x-test" }
android-x-testrules = { group = "androidx.test", name = "rules", version.ref = "android-x-testrules" }
android-x-test-ext-junitktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "android-x-test-ext-junitktx" }
android-x-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "android-x-test-espresso" }
android-x-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "android-x-annotation" }
android-x-testrunner = { group = "androidx.test", name = "runner", version.ref = "android-x-testrunner" }
awaitility = { group = "org.awaitility", name = "awaitility", version.ref = "awaitility" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
jackson-core = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson-core" }
jackson-module = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson-module" }
json-assert = { group = "org.skyscreamer", name = "jsonassert", version.ref = "json-assert" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent-jvm", version.ref = "mockk" }
moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi" }
moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshi" }
moshi = { group = "com.squareup.moshi", name = "moshi", version.ref = "moshi" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
work = { group = "androidx.work", name = "work-runtime", version.ref = "work" }
work-multiprocess = { group = "androidx.work", name = "work-multiprocess", version.ref = "work" }
work-test = { group = "androidx.work", name = "work-testing", version.ref = "work" }
runner = { group = "com.android.support.test", name = "runner", version.ref = "runner" }
com-android-support-test-espresso-espresso-core = { group = "com.android.support.test.espresso", name = "espresso-core", version.ref = "com-android-support-test-espresso-espresso-core" }
appcompat-v7 = { group = "com.android.support", name = "appcompat-v7", version.ref = "appcompat-v7" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
