[versions]

activity-compose = "1.9.3"
agp = "8.3.2"
android-core-ktx = "1.15.0"
foundation = "1.7.5"
json-assert = "1.5.0"
junit = "4.13.2"
kotlin = "1.9.0"
kotlinx-coroutines-core = "1.8.0"
kotlinx-serialization-json = "1.5.1"
lifecycle-process = "2.8.7"
lifecycle-viewmodel-compose = "2.8.7"
material = "1.12.0"
material-version = "1.7.5"
mockk = "1.13.7"
detekt = "1.23.6"
navigation = "2.8.4"
play-services-ads = "23.5.0"
ui = "1.7.5"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material-version" }
foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-core" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
android-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "android-core-ktx" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
json-assert = { group = "org.skyscreamer", name = "jsonassert", version.ref = "json-assert" }
lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycle-process" }
material = { module = "com.google.android.material:material", version.ref = "material" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-agent = { group = "io.mockk", name = "mockk-agent-jvm", version.ref = "mockk" }
navigation-runtime = { module = "androidx.navigation:navigation-runtime", version.ref = "navigation" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "play-services-ads" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "ui" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "ui" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
